server:
  port: 6877
eureka:
  instance:
    hostname: localhost
  client:
#  1.eureka.client.registerWithEureka=true #是否将自身注册
#  2.eureka.client.fetchRegistry=false #如果为true，启动时报警.
#  4.5打开eureka server 界面的
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/