eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6877/eureka/
  instance:
#    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    prefer-ip-address: true
    hostname: 192.168.2.15
server:
  port: 8762
spring:
  application:
    name: demo
  cloud:
    client:
      ipAddress: 192.168.2.15


feign:
   hystrix:
     enabled: true

