eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6877/eureka/
  instance:
    instance-id: 192.168.2.15
  #    将本机注册ip；IP注册到Eureka Server上
#    prefer-ip-address: true
#    hostname: 192.168.2.15
#    ip-address: 192.168.2.15
server:
  port: 8660
spring:
  application:
    name: admin
  boot:
    admin:
      auto-registration: true
      url: http://localhost:8661
      api-path: instances

feign:
   hystrix:
     enabled: true
management:
  security:
    enabled: false

