server:
  port: 8802
  context-path: /elastic


elastic:
#  hostlist: 192.168.0.109:9200
  ip: 192.168.0.109
  port: 9200
  cluster: LinkieBuy-cluster
  index: linkiebuy
  type: doc
  pageSize: 20
  userName: ''
  password: ''
  selfEs: true # 自己搭的es true, 阿里云es false